const menu = [
  {
    id: 1,
    title: "Fried rice",
    category: "rice",
    price: 21.99,
    img: require("../Images/FriedRice.jpg"),
    desc: "Fried rice with chicken and plantains",
  },
  {
    id: 2,
    title: "Jollof rice",
    category: "rice",
    price: 19.99,
    img: require("../Images/JollofRice_Chicken.jpg"),
    desc: "Jollof rice with chicken and plantains",
  },
  {
    id: 3,
    title: "Jollof rice",
    category: "rice",
    price: 22.99,
    img: require("../Images/Goatmeat_Jollof.jpeg"),
    desc: "Jollof rice with goat meat and plantains",
  },
  {
    id: 4,
    title: "Coconut rice",
    category: "rice",
    price: 19.99,
    img: require("../Images/Turkey_Jollof.jpg"),
    desc: "Coconut rice with turkey and plantains",
  },
  {
    id: 5,
    title: "White rice",
    category: "rice",
    price: 15.99,
    img: require("../Images/WhiteRice_Stew.jpg"),
    desc: "White rice with chicken stew and plantains",
  },
  {
    id: 6,
    title: "Egusi soup",
    category: "soup",
    price: 16.99,
    img: require("../Images/egusiSoup.jpg"),
    desc: "Egusi soup with assorted meat and garri",
  },
  {
    id: 7,
    title: "Vegetable soup",
    category: "soup",
    price: 20.99,
    img: require("../Images/VegetableSoup.jpg"),
    desc: "Vegetable soup with assorted meat and garri",
  },
  {
    id: 8,
    title: "Okro soup",
    category: "soup",
    price: 17.99,
    img: require("../Images/OkroSoup.jpg"),
    desc: "Okro soup with assorted meat and garri",
  },
  {
    id: 9,
    title: "Afang soup",
    category: "soup",
    price: 19.99,
    img: require("../Images/AfangSoup.jpg"),
    desc: "Afang soup with assorted meat and garri",
  },
  {
    id: 10,
    title: "Nsala soup",
    category: "soup",
    price: 15.99,
    img: require("../Images/NsalaSoup.jpg"),
    desc: "Nsala soup with assorted meat and garri",
  },
  {
    id: 11,
    title: "Ogbono soup",
    category: "soup",
    price: 17.99,
    img: require("../Images/OgbonoSoup.jpg"),
    desc: "Ogbono soup with assorted meat and garri",
  },
  {
    id: 12,
    title: "Meatpie",
    category: "snacks",
    price: 3.99,
    img: require("../Images/Meatpie.jpg"),
    desc: "Naija style meatpie",
  },
  {
    id: 13,
    title: "buns",
    category: "snacks",
    price: 3.99,
    img: require("../Images/Buns.jpeg"),
    desc: "Crunchy african snack made of fried dough.",
  },
  {
    id: 14,
    title: "Fish roll",
    category: "snacks",
    price: 3.99,
    img: require("../Images/FishRoll.jpg"),
    desc: "crunchy slight sweet and spicy pastry stuffed with fish ",
  },
  {
    id: 15,
    title: "puff puff",
    category: "snacks",
    price: 3.99,
    img: require("../Images/Puffpuff.jpg"),
    desc: "Traditional african snack made of fried dough. It is soft anf fluffy",
  },
  {
    id: 16,
    title: "Chicken",
    category: "sides",
    price: 10.99,
    img: require("../Images/chickenDrum.jpg"),
    desc: "Sweet and savory roasted chicken",
  },
  {
    id: 17,
    title: " White rice",
    category: "sides",
    price: 5.99,
    img: require("../Images/PlainWhiteRice.jpg"),
    desc: "Boiled white rice",
  },
  {
    id: 18,
    title: "Plantain",
    category: "sides",
    price: 4.99,
    img: require("../Images/FriedPlantain.jpg"),
    desc: "Fried plantains",
  },
  {
    id: 19,
    title: "Garri",
    category: "sides",
    price: 3.99,
    img: require("../Images/Garri.jpg"),
    desc: "",
  },
  {
    id: 20,
    title: "Nkwobi",
    category: "local dish",
    price: 10.99,
    img: require("../Images/nkwobi.jpg"),
    desc: "Cooked cow feet mixed in spicy palm oil paste",
  },
  {
    id: 21,
    title: "Suya",
    category: "local dish",
    price: 7.99,
    img: require("../Images/Suya.jpg"),
    desc: "Smoke spice meat skewer",
  },
  {
    id: 22,
    title: "Peppersoup",
    category: "local dish",
    price: 12.99,
    img: require("../Images/Peppersoup.jpg"),
    desc: "Spicy traditional drinking soup with assorted meat",
  },
  {
    id: 23,
    title: "Coca-cola",
    category: "drinks",
    price: 2.99,
    img: require("../Images/Cocacola.jpg"),
    desc: "",
  },
  {
    id: 24,
    title: "Pepsi",
    category: "drinks",
    price: 2.29,
    img: require("../Images/Pepsi.jpg"),
    desc: "",
  },
  {
    id: 25,
    title: "Mountain Dew",
    category: "drinks",
    price: 2.29,
    img: require("../Images/MountainDew.jpg"),
    desc: "",
  },
  {
    id: 26,
    title: "Dr Pepper",
    category: "drinks",
    price: 1.99,
    img: require("../Images/DrPepper.jpg"),
    desc: "",
  },
  {
    id: 27,
    title: "Diet coke",
    category: "drinks",
    price: 1.99,
    img: require("../Images/DietCoke.jpg"),
    desc: "",
  },
  {
    id: 28,
    title: "Sprite",
    category: "rice",
    price: 2.0,
    img: require("../Images/Sprite.jpg"),
    desc: "",
  },
];

export default menu;
